### ISSUE TITLE
Fehler bei Installation (ER2)

### ISSUE THREAD

**Issue by johannes-bittner** [dennis-sagasser/contao-room-reservation#4]
Von der Beschreibung her eine sehr interessante Erweiterung, leider folgende Fehler bei der Installation in einem aktuellen Contao 3.5.27 über das normale ER2:

> Warning: include(D:\htdocs/system/modules/room_reservation/library/RoomReservation/HooksRoomBackend.php): failed to open stream: No such file or directory in system\modules\core\library\Contao\ClassLoader.php on line 161
> 
> #0 system\modules\core\library\Contao\ClassLoader.php(161): __error(2, 'include(D:\\htdo...', 'D:\\htdocs\\...', 161, Array)
> #1 system\modules\core\library\Contao\ClassLoader.php(161): Contao\ClassLoader::load()
> #2 [internal function]: Contao\ClassLoader::load('HooksRoomBacken...')
> #3 [internal function]: spl_autoload_call('HooksRoomBacken...')
> #4 system\modules\core\library\Contao\System.php(140): get_class_methods('HooksRoomBacken...')
> #5 system\modules\core\classes\BackendTemplate.php(41): Contao\System->import('HooksRoomBacken...')
> #6 system\modules\core\library\Contao\Pagination.php(299): Contao\BackendTemplate->parse()
> #7 system\modules\core\classes\Versions.php(613): Contao\Pagination->generate()
> #8 system\modules\core\controllers\BackendMain.php(175): Contao\Versions::addToTemplate(Object(Contao\BackendTemplate))
> #9 system\modules\core\controllers\BackendMain.php(125): Contao\BackendMain->welcomeScreen()
> #10 contao\main.php(20): Contao\BackendMain->run()
> #11 {main}
> 
> 
> Warning: include(): Failed opening 'D:\htdocs/system/modules/room_reservation/library/RoomReservation/HooksRoomBackend.php' for inclusion (include_path='C:\xampp\php\PEAR') in system\modules\core\library\Contao\ClassLoader.php on line 161
> 
> #0 system\modules\core\library\Contao\ClassLoader.php(161): __error(2, 'include(): Fail...', 'D:\\htdocs\\...', 161, Array)
> #1 system\modules\core\library\Contao\ClassLoader.php(161): Contao\ClassLoader::load()
> #2 [internal function]: Contao\ClassLoader::load('HooksRoomBacken...')
> #3 [internal function]: spl_autoload_call('HooksRoomBacken...')
> #4 system\modules\core\library\Contao\System.php(140): get_class_methods('HooksRoomBacken...')
> #5 system\modules\core\classes\BackendTemplate.php(41): Contao\System->import('HooksRoomBacken...')
> #6 system\modules\core\library\Contao\Pagination.php(299): Contao\BackendTemplate->parse()
> #7 system\modules\core\classes\Versions.php(613): Contao\Pagination->generate()
> #8 system\modules\core\controllers\BackendMain.php(175): Contao\Versions::addToTemplate(Object(Contao\BackendTemplate))
> #9 system\modules\core\controllers\BackendMain.php(125): Contao\BackendMain->welcomeScreen()
> #10 contao\main.php(20): Contao\BackendMain->run()
> #11 {main}
> 
> 
> Warning: include(D:\htdocs/system/modules/room_reservation/library/RoomReservation/HooksRoomBackend.php): failed to open stream: No such file or directory in system\modules\core\library\Contao\ClassLoader.php on line 148
> 
> #0 system\modules\core\library\Contao\ClassLoader.php(148): __error(2, 'include(D:\\htdo...', 'D:\\htdocs\\...', 148, Array)
> #1 system\modules\core\library\Contao\ClassLoader.php(148): Contao\ClassLoader::load()
> #2 [internal function]: Contao\ClassLoader::load('Contao\\HooksRoo...')
> #3 [internal function]: spl_autoload_call('Contao\\HooksRoo...')
> #4 system\modules\core\library\Contao\ClassLoader.php(164): class_alias('Contao\\HooksRoo...', 'HooksRoomBacken...')
> #5 [internal function]: Contao\ClassLoader::load('HooksRoomBacken...')
> #6 [internal function]: spl_autoload_call('HooksRoomBacken...')
> #7 system\modules\core\library\Contao\System.php(140): get_class_methods('HooksRoomBacken...')
> #8 system\modules\core\classes\BackendTemplate.php(41): Contao\System->import('HooksRoomBacken...')
> #9 system\modules\core\library\Contao\Pagination.php(299): Contao\BackendTemplate->parse()
> #10 system\modules\core\classes\Versions.php(613): Contao\Pagination->generate()
> #11 system\modules\core\controllers\BackendMain.php(175): Contao\Versions::addToTemplate(Object(Contao\BackendTemplate))
> #12 system\modules\core\controllers\BackendMain.php(125): Contao\BackendMain->welcomeScreen()
> #13 contao\main.php(20): Contao\BackendMain->run()
> #14 {main}
> 
> 
> Warning: include(): Failed opening 'D:\htdocs/system/modules/room_reservation/library/RoomReservation/HooksRoomBackend.php' for inclusion (include_path='C:\xampp\php\PEAR') in system\modules\core\library\Contao\ClassLoader.php on line 148
> 
> #0 system\modules\core\library\Contao\ClassLoader.php(148): __error(2, 'include(): Fail...', 'D:\\htdocs\\...', 148, Array)
> #1 system\modules\core\library\Contao\ClassLoader.php(148): Contao\ClassLoader::load()
> #2 [internal function]: Contao\ClassLoader::load('Contao\\HooksRoo...')
> #3 [internal function]: spl_autoload_call('Contao\\HooksRoo...')
> #4 system\modules\core\library\Contao\ClassLoader.php(164): class_alias('Contao\\HooksRoo...', 'HooksRoomBacken...')
> #5 [internal function]: Contao\ClassLoader::load('HooksRoomBacken...')
> #6 [internal function]: spl_autoload_call('HooksRoomBacken...')
> #7 system\modules\core\library\Contao\System.php(140): get_class_methods('HooksRoomBacken...')
> #8 system\modules\core\classes\BackendTemplate.php(41): Contao\System->import('HooksRoomBacken...')
> #9 system\modules\core\library\Contao\Pagination.php(299): Contao\BackendTemplate->parse()
> #10 system\modules\core\classes\Versions.php(613): Contao\Pagination->generate()
> #11 system\modules\core\controllers\BackendMain.php(175): Contao\Versions::addToTemplate(Object(Contao\BackendTemplate))
> #12 system\modules\core\controllers\BackendMain.php(125): Contao\BackendMain->welcomeScreen()
> #13 contao\main.php(20): Contao\BackendMain->run()
> #14 {main}
> 
> 
> Warning: Class 'Contao\HooksRoomBackend' not found in system\modules\core\library\Contao\ClassLoader.php on line 164
> 
> #0 [internal function]: __error(2, 'Class 'Contao\\H...', 'D:\\htdocs\\...', 164, Array)
> #1 system\modules\core\library\Contao\ClassLoader.php(164): class_alias('Contao\\HooksRoo...', 'HooksRoomBacken...')
> #2 [internal function]: Contao\ClassLoader::load('HooksRoomBacken...')
> #3 [internal function]: spl_autoload_call('HooksRoomBacken...')
> #4 system\modules\core\library\Contao\System.php(140): get_class_methods('HooksRoomBacken...')
> #5 system\modules\core\classes\BackendTemplate.php(41): Contao\System->import('HooksRoomBacken...')
> #6 system\modules\core\library\Contao\Pagination.php(299): Contao\BackendTemplate->parse()
> #7 system\modules\core\classes\Versions.php(613): Contao\Pagination->generate()
> #8 system\modules\core\controllers\BackendMain.php(175): Contao\Versions::addToTemplate(Object(Contao\BackendTemplate))
> #9 system\modules\core\controllers\BackendMain.php(125): Contao\BackendMain->welcomeScreen()
> #10 contao\main.php(20): Contao\BackendMain->run()
> #11 {main}
> 
> 
> Warning: in_array() expects parameter 2 to be array, null given in system\modules\core\library\Contao\System.php on line 140
> 
> #0 [internal function]: __error(2, 'in_array() expe...', 'D:\\htdocs\\...', 140, Array)
> #1 system\modules\core\library\Contao\System.php(140): in_array('getInstance', NULL)
> #2 system\modules\core\classes\BackendTemplate.php(41): Contao\System->import('HooksRoomBacken...')
> #3 system\modules\core\library\Contao\Pagination.php(299): Contao\BackendTemplate->parse()
> #4 system\modules\core\classes\Versions.php(613): Contao\Pagination->generate()
> #5 system\modules\core\controllers\BackendMain.php(175): Contao\Versions::addToTemplate(Object(Contao\BackendTemplate))
> #6 system\modules\core\controllers\BackendMain.php(125): Contao\BackendMain->welcomeScreen()
> #7 contao\main.php(20): Contao\BackendMain->run()
> #8 {main}
> 
> 
> Warning: include(D:\htdocs/system/modules/room_reservation/library/RoomReservation/HooksRoomBackend.php): failed to open stream: No such file or directory in system\modules\core\library\Contao\ClassLoader.php on line 161
> 
> #0 system\modules\core\library\Contao\ClassLoader.php(161): __error(2, 'include(D:\\htdo...', 'D:\\htdocs\\...', 161, Array)
> #1 system\modules\core\library\Contao\ClassLoader.php(161): Contao\ClassLoader::load()
> #2 [internal function]: Contao\ClassLoader::load('HooksRoomBacken...')
> #3 system\modules\core\library\Contao\System.php(140): spl_autoload_call('HooksRoomBacken...')
> #4 system\modules\core\classes\BackendTemplate.php(41): Contao\System->import('HooksRoomBacken...')
> #5 system\modules\core\library\Contao\Pagination.php(299): Contao\BackendTemplate->parse()
> #6 system\modules\core\classes\Versions.php(613): Contao\Pagination->generate()
> #7 system\modules\core\controllers\BackendMain.php(175): Contao\Versions::addToTemplate(Object(Contao\BackendTemplate))
> #8 system\modules\core\controllers\BackendMain.php(125): Contao\BackendMain->welcomeScreen()
> #9 contao\main.php(20): Contao\BackendMain->run()
> #10 {main}
> 
> 
> Warning: include(): Failed opening 'D:\htdocs/system/modules/room_reservation/library/RoomReservation/HooksRoomBackend.php' for inclusion (include_path='C:\xampp\php\PEAR') in system\modules\core\library\Contao\ClassLoader.php on line 161
> 
> #0 system\modules\core\library\Contao\ClassLoader.php(161): __error(2, 'include(): Fail...', 'D:\\htdocs\\...', 161, Array)
> #1 system\modules\core\library\Contao\ClassLoader.php(161): Contao\ClassLoader::load()
> #2 [internal function]: Contao\ClassLoader::load('HooksRoomBacken...')
> #3 system\modules\core\library\Contao\System.php(140): spl_autoload_call('HooksRoomBacken...')
> #4 system\modules\core\classes\BackendTemplate.php(41): Contao\System->import('HooksRoomBacken...')
> #5 system\modules\core\library\Contao\Pagination.php(299): Contao\BackendTemplate->parse()
> #6 system\modules\core\classes\Versions.php(613): Contao\Pagination->generate()
> #7 system\modules\core\controllers\BackendMain.php(175): Contao\Versions::addToTemplate(Object(Contao\BackendTemplate))
> #8 system\modules\core\controllers\BackendMain.php(125): Contao\BackendMain->welcomeScreen()
> #9 contao\main.php(20): Contao\BackendMain->run()
> #10 {main}
> 
> 
> Warning: include(D:\htdocs/system/modules/room_reservation/library/RoomReservation/HooksRoomBackend.php): failed to open stream: No such file or directory in system\modules\core\library\Contao\ClassLoader.php on line 148
> 
> #0 system\modules\core\library\Contao\ClassLoader.php(148): __error(2, 'include(D:\\htdo...', 'D:\\htdocs\\...', 148, Array)
> #1 system\modules\core\library\Contao\ClassLoader.php(148): Contao\ClassLoader::load()
> #2 [internal function]: Contao\ClassLoader::load('Contao\\HooksRoo...')
> #3 [internal function]: spl_autoload_call('Contao\\HooksRoo...')
> #4 system\modules\core\library\Contao\ClassLoader.php(164): class_alias('Contao\\HooksRoo...', 'HooksRoomBacken...')
> #5 [internal function]: Contao\ClassLoader::load('HooksRoomBacken...')
> #6 system\modules\core\library\Contao\System.php(140): spl_autoload_call('HooksRoomBacken...')
> #7 system\modules\core\classes\BackendTemplate.php(41): Contao\System->import('HooksRoomBacken...')
> #8 system\modules\core\library\Contao\Pagination.php(299): Contao\BackendTemplate->parse()
> #9 system\modules\core\classes\Versions.php(613): Contao\Pagination->generate()
> #10 system\modules\core\controllers\BackendMain.php(175): Contao\Versions::addToTemplate(Object(Contao\BackendTemplate))
> #11 system\modules\core\controllers\BackendMain.php(125): Contao\BackendMain->welcomeScreen()
> #12 contao\main.php(20): Contao\BackendMain->run()
> #13 {main}
> 
> 
> Warning: include(): Failed opening 'D:\htdocs/system/modules/room_reservation/library/RoomReservation/HooksRoomBackend.php' for inclusion (include_path='C:\xampp\php\PEAR') in system\modules\core\library\Contao\ClassLoader.php on line 148
> 
> #0 system\modules\core\library\Contao\ClassLoader.php(148): __error(2, 'include(): Fail...', 'D:\\htdocs\\...', 148, Array)
> #1 system\modules\core\library\Contao\ClassLoader.php(148): Contao\ClassLoader::load()
> #2 [internal function]: Contao\ClassLoader::load('Contao\\HooksRoo...')
> #3 [internal function]: spl_autoload_call('Contao\\HooksRoo...')
> #4 system\modules\core\library\Contao\ClassLoader.php(164): class_alias('Contao\\HooksRoo...', 'HooksRoomBacken...')
> #5 [internal function]: Contao\ClassLoader::load('HooksRoomBacken...')
> #6 system\modules\core\library\Contao\System.php(140): spl_autoload_call('HooksRoomBacken...')
> #7 system\modules\core\classes\BackendTemplate.php(41): Contao\System->import('HooksRoomBacken...')
> #8 system\modules\core\library\Contao\Pagination.php(299): Contao\BackendTemplate->parse()
> #9 system\modules\core\classes\Versions.php(613): Contao\Pagination->generate()
> #10 system\modules\core\controllers\BackendMain.php(175): Contao\Versions::addToTemplate(Object(Contao\BackendTemplate))
> #11 system\modules\core\controllers\BackendMain.php(125): Contao\BackendMain->welcomeScreen()
> #12 contao\main.php(20): Contao\BackendMain->run()
> #13 {main}
> 
> 
> Warning: Class 'Contao\HooksRoomBackend' not found in system\modules\core\library\Contao\ClassLoader.php on line 164
> 
> #0 [internal function]: __error(2, 'Class 'Contao\\H...', 'D:\\htdocs\\...', 164, Array)
> #1 system\modules\core\library\Contao\ClassLoader.php(164): class_alias('Contao\\HooksRoo...', 'HooksRoomBacken...')
> #2 [internal function]: Contao\ClassLoader::load('HooksRoomBacken...')
> #3 system\modules\core\library\Contao\System.php(140): spl_autoload_call('HooksRoomBacken...')
> #4 system\modules\core\classes\BackendTemplate.php(41): Contao\System->import('HooksRoomBacken...')
> #5 system\modules\core\library\Contao\Pagination.php(299): Contao\BackendTemplate->parse()
> #6 system\modules\core\classes\Versions.php(613): Contao\Pagination->generate()
> #7 system\modules\core\controllers\BackendMain.php(175): Contao\Versions::addToTemplate(Object(Contao\BackendTemplate))
> #8 system\modules\core\controllers\BackendMain.php(125): Contao\BackendMain->welcomeScreen()
> #9 contao\main.php(20): Contao\BackendMain->run()
> #10 {main}
> 
> 
> Fatal error: Class 'HooksRoomBackend' not found in D:\htdocs\system\modules\core\library\Contao\System.php on line 140

**Comment by dennis-sagasser** [comment]
Die Installation per ER2 sollte nun laufen. Ich hatte beim Veröffentlichen der Dateien den vorgeschlagenen falschen Pfad (TL_ROOT/system/modules/**reservation**/) übernommen. Jetzt ist er korrekt: TL_ROOT/system/modules/**room_reservation**. Leider klappt das aber irgendwie nicht bei der Installation via Composer. Dort zieht er immernoch den alten Ordner. Vorläufige Abhilfe schafft aber das Umbenennen von /system/modules/reservation in /system/modules/**room_reservation**.
